# Generated by Django 5.0.4 on 2024-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_followers_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#BA9797', max_length=7, verbose_name='Цвет фона'),
        ),
    ]
