# Generated by Django 5.0.4 on 2024-06-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_publications_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-id'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
